GLOBAL_LIST_INIT(psychonaut_traits, list(
	/mob = list(
		"TRAIT_CAN_USE_JUKEBOX" = TRAIT_CAN_USE_JUKEBOX,
		"TRAIT_NOTOOLFLASH" = TRAIT_NOTOOLFLASH,
		"TRAIT_CANT_ATTACK" = TRAIT_CANT_ATTACK,
		"TRAIT_CLOWNING" = TRAIT_CLOWNING
	),
	/atom/movable = list(
		"TRAIT_GRABBED_BY_KINESIS" = TRAIT_GRABBED_BY_KINESIS,
	),
))
