[animal]
name = "Animal"
path = "sound/_psychonaut/animal"

[animal.chirp]
name = "Chirp"
path = "chirp.ogg"
volume = 0.3

[animal.caw]
name = "Caw"
path = "caw.ogg"
min_pitch = 0.5
max_pitch = 1.3
min_speed = 6
volume = 0.25

[animal.chittery]
name = "Chittery"
path = "mothchitter2.ogg"
min_pitch = 1
max_pitch = 1.3
volume = 0.3

[animal.chitter]
name = "Chitter"
path = "chitter.ogg"
min_pitch = 1
max_pitch = 1.3
volume = 0.3

[animal.meow]
name = "Meow"
path = "meow1.ogg"
min_pitch = 0.8
max_pitch = 1.2
volume = 0.3

[animal.mothsqueak]
name = "Mothsqueak"
path = "mothsqueak.ogg"
min_pitch = 0.9
max_pitch = 1.3
volume = 0.3

[dont_starve]
name = "Don't Starve"
path = "sound/_psychonaut/dont_starve"

[dont_starve.wilson]
name = "Wilson"
path = "wilson.ogg"
volume = 0.2

[dont_starve.wolfgang]
name = "Wolfgang"
path = "wolfgang.ogg"
volume = 0.15

[dont_starve.woodie]
name = "Woodie"
path = "woodie.ogg"
volume = 0.1

[dont_starve.wurt]
name = "Wurt"
path = "wurt.ogg"
volume = 0.1

[dont_starve.wx78]
name = "WX78"
path = "wx78.ogg"
volume = 0.05

[talk]
name = "Talk"
path = "sound/_psychonaut/talk"

[talk.blub]
name = "Blub"
path = "blub.ogg"
ask_path = "blub_ask.ogg"
exclaim_path = "blub_exclaim.ogg"
min_pitch = 0.7
volume = 0.4

[talk.bottalk_1]
name = "Bottalk 1"
path = "bottalk_1.ogg"
ask_path = "bottalk_3.ogg"
exclaim_path = "bottalk_2.ogg"
min_speed = 3
max_speed = 9
min_pitch = 0.5
volume = 0.4

[talk.bottalk_2]
name = "Bottalk 2"
path = "bottalk_2.ogg"
min_pitch = 0.9

[talk.bottalk_3]
name = "Bottalk 3"
path = "bottalk_3.ogg"
min_pitch = 0.6

[talk.buwoo]
name = "Buwoo"
path = "buwoo.ogg"
ask_path = "buwoo_ask.ogg"
exclaim_path = "buwoo_exclaim.ogg"
min_pitch = 0.8

[talk.cow]
name = "Cow"
path = "cow.ogg"
ask_path = "cow_ask.ogg"
exclaim_path = "cow_exclaim.ogg"
min_pitch = 0.8

[talk.cyborg]
name = "Cyborg"
path = "cyborg.ogg"
ask_path = "cyborg_ask.ogg"
exclaim_path = "cyborg_exclaim.ogg"
min_pitch = 0.6
volume = 0.4

[talk.lizard]
name = "Lizard"
path = "lizard.ogg"
ask_path = "lizard_ask.ogg"
exclaim_path = "lizard_exclaim.ogg"
min_pitch = 0.6

[talk.pug]
name = "Pug"
path = "pug.ogg"
ask_path = "pug_ask.ogg"
exclaim_path = "pug_exclaim.ogg"
min_pitch = 0.7

[talk.pugg]
name = "Pugg"
path = "pugg.ogg"
ask_path = "pugg_ask.ogg"
exclaim_path = "pugg_exclaim.ogg"
min_pitch = 0.6

[talk.radio]
name = "Radio"
path = "radio.ogg"
hidden = true

[talk.radio2]
name = "Radio2"
path = "radio2.ogg"
hidden = true

[talk.radio_ai]
name = "Radio Ai"
path = "radio_ai.ogg"
hidden = true

[talk.roach]
name = "Roach"
path = "roach.ogg"
ask_path = "roach_ask.ogg"
exclaim_path = "roach_exclaim.ogg"
hidden = true

[talk.skelly]
name = "Skelly"
path = "skelly.ogg"
ask_path = "skelly_ask.ogg"
exclaim_path = "skelly_exclaim.ogg"
min_pitch = 0.6

[talk.speak_1]
name = "Speak 1"
path = "speak_1.ogg"
ask_path = "speak_1_ask.ogg"
exclaim_path = "speak_1_exclaim.ogg"
allow_random = true
min_pitch = 0.6

[talk.speak_2]
name = "Speak 2"
path = "speak_2.ogg"
ask_path = "speak_2_ask.ogg"
exclaim_path = "speak_2_exclaim.ogg"
allow_random = true
min_pitch = 0.5

[talk.speak_3]
name = "Speak 3"
path = "speak_3.ogg"
ask_path = "speak_3_ask.ogg"
exclaim_path = "speak_3_exclaim.ogg"
allow_random = true
min_pitch = 0.5

[talk.speak_4]
name = "Speak 4"
path = "speak_4.ogg"
ask_path = "speak_4_ask.ogg"
exclaim_path = "speak_4_exclaim.ogg"
allow_random = true
min_pitch = 0.6
