#define VOICE_DEFAULT_MINPITCH 0.4
#define VOICE_DEFAULT_MAXPITCH 2
#define VOICE_DEFAULT_MINVARY 0.1
#define VOICE_DEFAULT_MAXVARY 0.8
#define VOICE_DEFAULT_MINSPEED 4
#define VOICE_DEFAULT_MAXSPEED 16
