#define WEB_SOUND_ERR_YTDL_NOT_CONFIGURED 1
#define WEB_SOUND_ERR_INVALID_URL 2
#define WEB_SOUND_ERR_NOT_HTTPS 3
#define WEB_SOUND_ERR_JSON_RETRIEVAL 4
#define WEB_SOUND_ERR_JSON_PARSING 5
#define WEB_SOUND_ERR_DURATION 6

#define WEB_SOUND_CACHE_DURATION 4 MINUTES
#define WEB_SOUND_MAX_DURATION 10 MINUTES
