//Communication
#define COMSIG_KB_CLIENT_LOOC_DOWN "keybinding_client_looc_down"

//Livingzx
#define COMSIG_KB_LIVING_ITEM_PIXEL_SHIFT_DOWN "keybinding_living_item_pixelshift_down"
#define COMSIG_KB_LIVING_PIXEL_SHIFT_DOWN "keybinding_living_pixelshift_down"
#define COMSIG_KB_LIVING_FACECURSOR_DOWN "keybinding_living_facecursor_down"
