#define SFX_BULLET_IMPACT_ICE "bullet_impact_ice"
#define SFX_BULLET_IMPACT_WOOD "bullet_impact_wood"
#define SFX_BULLET_IMPACT_METAL "bullet_impact_metal"
#define SFX_BULLET_IMPACT_GLASS "bullet_impact_glass"
#define SFX_BULLET_IMPACT_CONCRETE "bullet_impact_concrete"
#define SFX_BULLET_IMPACT_FLESH "bullet_impact_flesh"
#define SFX_BULLET_IMPACT_STONE "bullet_impact_stone"
#define SFX_BULLET_IMPACT_WATER "bullet_impact_water"
